// frontend-web/src/utils/icons.js
import {
  ComputerDesktopIcon,
  HeartIcon,
  AcademicCapIcon,
  WrenchScrewdriverIcon,
  PaintBrushIcon,
  UserGroupIcon,
  BuildingOfficeIcon,
  ChartBarIcon,
  CodeBracketIcon,
  ServerIcon,
  BeakerIcon,
  UserIcon,
  BookOpenIcon,
  PencilIcon,
  CalculatorIcon,
  BuildingOffice2Icon,
  BoltIcon,
  MegaphoneIcon,
  NewspaperIcon,
  BuildingLibraryIcon,
  UsersIcon,
  MapIcon,
  FireIcon,
  RocketLaunchIcon,
  SparklesIcon,
  TrophyIcon,
  ClockIcon,
  CurrencyDollarIcon,
  ArrowTrendingUpIcon,
  BriefcaseIcon,
  ChartPieIcon,
  DocumentTextIcon,
  FolderIcon,
  QuestionMarkCircleIcon,
  CheckCircleIcon,
  XCircleIcon,
  InformationCircleIcon,
  ExclamationTriangleIcon,
  ArrowPathIcon,
  MagnifyingGlassIcon,
  FunnelIcon,
  ChevronDownIcon,
  ChevronRightIcon,
  ChevronLeftIcon,
  HomeIcon,
  Cog6ToothIcon,
  BellIcon,
  EnvelopeIcon,
  CalendarIcon,
  MapPinIcon,
  TagIcon,
  StarIcon,
  ArrowRightOnRectangleIcon,
  XMarkIcon,
  Bars3Icon
} from '@heroicons/react/24/outline';

// Export each icon individually
export {
  ComputerDesktopIcon,
  HeartIcon,
  AcademicCapIcon,
  WrenchScrewdriverIcon,
  PaintBrushIcon,
  UserGroupIcon,
  BuildingOfficeIcon,
  ChartBarIcon,
  CodeBracketIcon,
  ServerIcon,
  BeakerIcon,
  UserIcon,
  BookOpenIcon,
  PencilIcon,
  CalculatorIcon,
  BuildingOffice2Icon,
  BoltIcon,
  MegaphoneIcon,
  NewspaperIcon,
  BuildingLibraryIcon,
  UsersIcon,
  MapIcon,
  FireIcon,
  RocketLaunchIcon,
  SparklesIcon,
  TrophyIcon,
  ClockIcon,
  CurrencyDollarIcon,
  ArrowTrendingUpIcon,
  BriefcaseIcon,
  ChartPieIcon,
  DocumentTextIcon,
  FolderIcon,
  QuestionMarkCircleIcon,
  CheckCircleIcon,
  XCircleIcon,
  InformationCircleIcon,
  ExclamationTriangleIcon,
  ArrowPathIcon,
  MagnifyingGlassIcon,
  FunnelIcon,
  ChevronDownIcon,
  ChevronRightIcon,
  ChevronLeftIcon,
  HomeIcon,
  Cog6ToothIcon,
  BellIcon,
  EnvelopeIcon,
  CalendarIcon,
  MapPinIcon,
  TagIcon,
  StarIcon,
  ArrowRightOnRectangleIcon,
  XMarkIcon,
  Bars3Icon
};

// Also export as an object for convenience
export const Icons = {
  Technology: ComputerDesktopIcon,
  Health: HeartIcon,
  Education: AcademicCapIcon,
  Engineering: WrenchScrewdriverIcon,
  Arts: PaintBrushIcon,
  Social: UserGroupIcon,
  Hospitality: BuildingOfficeIcon,
  Business: ChartBarIcon,
  
  // Courses
  BSIT: ComputerDesktopIcon,
  BSCS: CodeBracketIcon,
  BSIS: ServerIcon,
  BSN: HeartIcon,
  BSMLS: BeakerIcon,
  BSPT: UserIcon,
  BEED: BookOpenIcon,
  BSEDEnglish: PencilIcon,
  BSEDMath: CalculatorIcon,
  BSCE: BuildingOffice2Icon,
  BSME: WrenchScrewdriverIcon,
  BSEE: BoltIcon,
  ABComm: MegaphoneIcon,
  ABJourn: NewspaperIcon,
  BFA: PaintBrushIcon,
  ABPsych: UserGroupIcon,
  ABPolSci: BuildingLibraryIcon,
  ABSociology: UsersIcon,
  BSHM: BuildingOfficeIcon,
  BST: MapIcon,
  BSCA: FireIcon,
  BSBA: ChartBarIcon,
  BSA: CalculatorIcon,
  BSEntrep: RocketLaunchIcon,
  
  // UI Elements
  Dashboard: HomeIcon,
  Assessment: SparklesIcon,
  Results: ChartPieIcon,
  Profile: UserIcon,
  Settings: Cog6ToothIcon,
  Notification: BellIcon,
  Email: EnvelopeIcon,
  Calendar: CalendarIcon,
  Location: MapPinIcon,
  Tag: TagIcon,
  Star: StarIcon,
  
  // Status
  Success: CheckCircleIcon,
  Error: XCircleIcon,
  Warning: ExclamationTriangleIcon,
  Info: InformationCircleIcon,
  Loading: ArrowPathIcon,
  
  // Actions
  Search: MagnifyingGlassIcon,
  Filter: FunnelIcon,
  ChevronDown: ChevronDownIcon,
  ChevronRight: ChevronRightIcon,
  ChevronLeft: ChevronLeftIcon,
  XMark: XMarkIcon,
  Bars3: Bars3Icon,
  Logout: ArrowRightOnRectangleIcon,
  
  // Career
  Career: BriefcaseIcon,
  Salary: CurrencyDollarIcon,
  Demand: ArrowTrendingUpIcon,
  Time: ClockIcon,
  Trophy: TrophyIcon,
  Document: DocumentTextIcon,
  Folder: FolderIcon,
  Question: QuestionMarkCircleIcon,
  
  // Additional icons
  UserCircleIcon: UserIcon,
  ArrowRightIcon: ChevronRightIcon,
};